/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    orders: Order;
    'pickup-slots': PickupSlot;
    locations: Location;
    categories: Category;
    products: Product;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'pickup-slots': PickupSlotsSelect<false> | PickupSlotsSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'shop-settings': ShopSetting;
  };
  globalsSelect: {
    'shop-settings': ShopSettingsSelect<false> | ShopSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  reference?: string | null;
  /**
   * Le passage à « Payée » est fait automatiquement à la confirmation du paiement Stripe. Seuls les changements de statut cohérents sont acceptés.
   */
  status: 'en_attente_paiement' | 'payee' | 'preparee' | 'retiree' | 'non_retiree' | 'annulee' | 'remboursee';
  pickupSlot: number | PickupSlot;
  customer: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
  };
  items: {
    product?: (number | null) | Product;
    productName: string;
    unitPriceCents: number;
    quantity: number;
    lineTotalCents: number;
    id?: string | null;
  }[];
  totalCents: number;
  customerNote?: string | null;
  /**
   * Visible uniquement dans le back-office.
   */
  internalNote?: string | null;
  expiresAt?: string | null;
  paidAt?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  termsAcceptedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-slots".
 */
export interface PickupSlot {
  id: number;
  title?: string | null;
  date: string;
  location: number | Location;
  /**
   * HH:mm
   */
  startTime: string;
  /**
   * HH:mm
   */
  endTime: string;
  /**
   * Laisser vide pour appliquer la règle des réglages boutique (par défaut la veille à 18:00).
   */
  orderDeadline?: string | null;
  /**
   * Optionnel. Laisser vide pour ne pas limiter.
   */
  maxOrders?: number | null;
  /**
   * Optionnel. Ex. 20 brioches au maximum pour ce passage.
   */
  productLimits?:
    | {
        product: number | Product;
        maxQuantity: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. « Le camion sera exceptionnellement devant la mairie ».
   */
  publicNote?: string | null;
  isOpen?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  _order?: string | null;
  /**
   * Nom affiché au client, en général le village (ex. « Montgeroult »).
   */
  name: string;
  /**
   * Ex. « Place de l’église, 95650 Montgeroult ».
   */
  address: string;
  /**
   * Précisions pour trouver le camion (optionnel).
   */
  directions?: string | null;
  /**
   * Un lieu inactif et ses passages ne sont plus proposés aux clients.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Généré depuis le nom à la création, puis stable.
   */
  slug?: string | null;
  category: number | Category;
  /**
   * Prix de vente TTC en euros (ex. 2,50).
   */
  priceCents: number;
  /**
   * Ex. « pièce », « 400 g », « 6 parts ».
   */
  unitLabel?: string | null;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Affichés au client avant l’achat. Laisser vide si aucun.
   */
  allergens?:
    | (
        | 'gluten'
        | 'crustaces'
        | 'oeufs'
        | 'poissons'
        | 'arachides'
        | 'soja'
        | 'lait'
        | 'fruits_a_coque'
        | 'celeri'
        | 'moutarde'
        | 'sesame'
        | 'sulfites'
        | 'lupin'
        | 'mollusques'
      )[]
    | null;
  /**
   * Décocher pour retirer le produit de la vente sans le supprimer.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pickup-slots';
        value: number | PickupSlot;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  reference?: T;
  status?: T;
  pickupSlot?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
      };
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        unitPriceCents?: T;
        quantity?: T;
        lineTotalCents?: T;
        id?: T;
      };
  totalCents?: T;
  customerNote?: T;
  internalNote?: T;
  expiresAt?: T;
  paidAt?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  termsAcceptedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pickup-slots_select".
 */
export interface PickupSlotsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  location?: T;
  startTime?: T;
  endTime?: T;
  orderDeadline?: T;
  maxOrders?: T;
  productLimits?:
    | T
    | {
        product?: T;
        maxQuantity?: T;
        id?: T;
      };
  publicNote?: T;
  isOpen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  address?: T;
  directions?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  category?: T;
  priceCents?: T;
  unitLabel?: T;
  description?: T;
  image?: T;
  allergens?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings".
 */
export interface ShopSetting {
  id: number;
  shopName: string;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Appliquée à chaque nouveau passage dont la date limite est laissée vide. Modifiable ensuite passage par passage.
   */
  defaultDeadline: {
    /**
     * 0 = le jour même, 1 = la veille…
     */
    daysBefore: number;
    /**
     * Format HH:mm, heure de Paris (ex. 18:00).
     */
    time: string;
  };
  /**
   * Doivent mentionner que le droit de rétractation ne s’applique pas aux denrées périssables.
   */
  termsOfSale?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shop-settings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  shopName?: T;
  contactEmail?: T;
  contactPhone?: T;
  defaultDeadline?:
    | T
    | {
        daysBefore?: T;
        time?: T;
      };
  termsOfSale?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}